apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-policy
  namespace: kube-system
data:
  audit-policy.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    rules:
      - level: Metadata
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        resources:
          - group: ""
            resources: ["pods", "services", "configmaps", "secrets", "namespaces"]
          - group: "apps"
            resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
          - group: "networking.k8s.io"
            resources: ["ingresses", "networkpolicies"]
          - group: "rbac.authorization.k8s.io"
            resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
        namespaces: ["default", "kube-system", "enterprise-security"]

      - level: RequestResponse
        verbs: ["create", "update", "patch", "delete"]
        resources:
          - group: ""
            resources: ["pods", "services", "secrets"]
        users: ["system:anonymous"]
        userGroups: ["system:unauthenticated"]

      - level: Request
        verbs: ["create", "update", "patch", "delete"]
        resources:
          - group: ""
            resources: ["namespaces"]

      - level: Request
        verbs: ["create", "update", "patch"]
        resources:
          - group: "rbac.authorization.k8s.io"
            resources: ["clusterroles", "clusterrolebindings"]

      - level: None
        verbs: ["get", "list", "watch"]
        resources:
          - group: ""
            resources: ["events", "endpoints"]
        namespaces: ["kube-system"]

      - level: None
