apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits-standard
  namespace: default
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "128Mi"
      cpu: "125m"
    type: Container
  - max:
      memory: "1024Mi"
      cpu: "1000m"
    min:
      memory: "64Mi"
      cpu: "50m"
    type: Container
