apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: prod

patchesStrategicMerge:
  - prod-patches.yaml

images:
  - name: backend-api
    newTag: latest
  - name: frontend
    newTag: latest
