apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Environment-specific labels
commonLabels:
  environment: sandbox

# Patches for sandbox environment
patchesStrategicMerge:
  - sandbox-patches.yaml

# Images for sandbox
images:
  - name: backend-api
    newTag: sandbox
  - name: frontend
    newTag: sandbox
