apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log all requests at the Metadata level
  - level: Metadata
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["pods", "services", "configmaps", "secrets"]
      - group: "apps"
        resources: ["deployments", "replicasets", "statefulsets"]
      - group: "networking.k8s.io"
        resources: ["ingresses", "networkpolicies"]
    namespaces: ["default", "kube-system"]

  # Log all authentication and authorization decisions
  - level: RequestResponse
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["pods", "services", "secrets"]
    users: ["system:anonymous"]
    userGroups: ["system:unauthenticated"]

  # Log all namespace changes
  - level: Request
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["namespaces"]

  # Don't log requests to certain system endpoints
  - level: None
    verbs: ["get", "list", "watch"]
    resources:
      - group: ""
        resources: ["events"]
    namespaces: ["kube-system"]

  # Default rule - log nothing else
  - level: None
