apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-api-deployment.yaml
  - frontend-deployment.yaml
  - postgres-deployment.yaml
  - prometheus-basic.yaml
  - fullstack-ingress.yaml
  - letsencrypt-prod-issuer.yaml

patchesStrategicMerge:
  - security-patches.yaml

# Common labels
commonLabels:
  app: tca-infraforge
  environment: base

# Namespace
namespace: tca-infraforge
