apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-config
  namespace: kube-system
data:
  pod-security-admission-config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
    - name: PodSecurity
      configuration:
        apiVersion: pod-security.admission.config.k8s.io/v1beta1
        kind: PodSecurityConfiguration
        defaults:
          enforce: "restricted"
          enforce-version: "latest"
          audit: "restricted"
          audit-version: "latest"
          warn: "restricted"
          warn-version: "latest"
        exemptions:
          usernames: ["system:serviceaccount:kube-system:*"]
          runtimeClasses: []
          namespaces: ["kube-system", "enterprise-security"]
